# Generated by Django 2.0.8 on 2018-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181126_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
