# Generated by Django 2.0.8 on 2018-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181128_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
