# Generated by Django 2.0.8 on 2019-02-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
