# Generated by Django 2.0.8 on 2018-11-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
