# Generated by Django 2.0.8 on 2018-11-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adds', '0003_auto_20181127_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author',
        ),
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='adds', to=settings.AUTH_USER_MODEL),
        ),
    ]
