# Generated by Django 2.0.8 on 2018-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_auto_20181128_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='sku',
            field=models.CharField(default='', max_length=50),
        ),
    ]
