# Generated by Django 2.0.8 on 2018-11-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_ad_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Oil', 'Oil'), ('Wine', 'Wine'), ('Cheese', 'Cheese')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
