# Generated by Django 2.0.8 on 2018-12-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sku', models.CharField(default='', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6)),
                ('category', models.CharField(choices=[('Oil', 'Oil'), ('Wine', 'Wine'), ('Cheese', 'Cheese')], max_length=10)),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_publish', 'Can publish an ad for a product'),),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product')),
            ],
        ),
    ]
